### ISSUE TITLE
Outstanding comments in the OCaml Multicore PR

### ISSUE THREAD

**Issue by abbysmal** [ocaml/ocaml#10861]
This issue aims to record and document outstanding comments in the Multicore PR (see #10831), in the case a merge makes it harder for the teams to dig them out from the Github UI.

This list should be exhaustive, however there may be some bits missing. Hopefully the PR remains usable after our last push and subsequent merge.
Anyone mentioned here, feel free to take a look at the list including your names and see if I missed anything in the process.

- [x] runtime/startup_aux.c:123 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-846588301 (fixed in #10873)
      @damiendoligez : `I don't understand this change. It seems to me that empty clauses are handled by line 121.`

- [x] stdlib/camlinternalAtomic.ml:5 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-846594578
       @damiendoligez @gadmm : `Should probably add the copyright of Cambridge and/or Stephen Dolan. cc @stedolan`

- [x] stdlib/filename.ml:103 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-846611187
     @damiendoligez @xavierleroy : `This is another recent change in 4.x that was not picked in Multicore.`

- [x] runtime/domain.c:1455 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-845798450
     @damiendoligez : `That doesn't leave any room for the id added by caml_thread_setname. Not sure if this is important, though.`

- [x] runtime/eventlog.c:370 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-845810712 (implemented in #10964)
      @damiendoligez : `These counters give information about the allocation patterns of the OCaml program, not about the allocator itself. So yes, we do want them in Multicore, eventually.`

- [x] runtime/fail_nat.c:207 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-845827892
      @damiendoligez : `To do: change this into a call to caml_fatal_error.`

- [x] runtime/fiber.c:101 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-845852150 (transferred to #11779)
      @damiendoligez : `Assumes 64-bit words.`

- [x] runtime/fiber.c:168 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-845850815 (transferred to #11779)
      @damiendoligez : `This assumes a 64-bit word size, right?`

- [x] runtime/io.c:552 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-845922223
      @kayceesrk : `This condition is missing in multicore, possibly lost in the rebase. Looks like the changes from this PR were not included in multicore: https://github.com/ocaml/ocaml/pull/10136/files. `

- [x] https://github.com/ocaml/ocaml/pull/10831#issuecomment-1007304534
      @shindere `Naked pointers are not allowed in OCaml Multicore. Now that we are about to merge, shoulnd't it be updated to juss say that naked pointers are no longer supported, if I understand correctly?` (fixed in #10962)

- [ ] asmcomp/cmm_helpers.ml:2206 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-839078245
      @kayceesrk @ctk21 `Related discussion: https://github.com/ocaml/ocaml/pull/10831/#discussion_r777185977. (Github UI renders the URL wrong).`

- [x] testsuite/tests/c-api/alloc_async.ml:1 https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-839177647 (re-enabled in #11596)
      @kayceesrk `Are we sure this is meant to be skipped?`

- [ ] .gitattributes:193 https://github.com/ocaml/ocaml/pull/10831#discussion_r774647041
      @dra27 `Is there a task to tidy this up? We should either generate this in the build (which I think is hard and possibly unnecessary) or the script which generates it ought to satisfy check-typo. If it is a committed generated file, CI should check its consistency (I'm volunteering, if necessary...)`

- [x] configure.ac:304 https://github.com/ocaml/ocaml/pull/10831#discussion_r774656781
       @dra27 `This doesn't quite do what's intended (in passing, I see the spacetime one is wrong too, which is embarrassing given that I wrote it!):` (see #10962)

- [x] runtime/caml/memory.h:21 https://github.com/ocaml/ocaml/pull/10831#discussion_r774658945
       @dra27 `Is this correct?` (addressed in #10863)

- [x] runtime/caml/ui.h: https://github.com/ocaml/ocaml/pull/10831#discussion_r775542572
      @dra27 @xavierleroy `The whole runtime/caml/ui.h should be removed, as well as its inclusion in runtime/startup_nat.h. It's a leftover from very old times.`

- [ ] otherlibs/unix/fork.c:41 https://github.com/ocaml/ocaml/pull/10831#discussion_r774698250
      @xavierleroy `Should it be failwith or invalid_argument or a Unix error code like ENOTSUPP ? I don't know yet, just making a note to think about it later.`
      
- [x] otherlibs/unix/unixsupport.c:296 https://github.com/ocaml/ocaml/pull/10831#discussion_r774700458
      @xavierleroy `That's OK for the time being. Later, either check that caml_named_value is fast enough (currently it uses a rather primitive hash table implementation) or consider caching the result in thread-local storage or in global storage but with atomic update.` (#11056)

- [x] runtime/eventlog.c:199 https://github.com/ocaml/ocaml/pull/10831#discussion_r774784931 (`eventlog.c` removed in #10964)
      @avsm `isn't caml_stat_alloc and raising Out_of_memory shorter and a more accurate exception here? (the backtrace will reveal where the mem alloc failed)`

- [x] runtime/caml/sync.h:82 https://github.com/ocaml/ocaml/pull/10831#discussion_r774789429
      @edwintorok `If this is called in a multithreaded program it should call strerror_r: the value returned by strerror could change if another thread calls strerror meanwhile, man 3p strerror says:` (#11010).
     
- [x] runtime/fiber.c:77 https://github.com/ocaml/ocaml/pull/10831#discussion_r775046254
      @avsm `For OpenBSD support, we're going to need to allocate this stack memory with mmap(..., MAP_STACK|MAP_ANON|MAP_PRIVATE) or else the process is killed by the syscall entry function. I've got a patch for this locally on OpenBSD but am not sure of the performance impact of switching to mmap for every OS or if we should just do that for OpenBSD.`

- [x] runtime/addrmap.c:27 https://github.com/ocaml/ocaml/pull/10831#discussion_r775441447 (addressed in #11650)
      @xavierleroy `Where does this hash function comes from? The "multiply by 0xcc9e2d51" is also in Murmurhash 3, but not the "shift and xor". It would be nice to give a reference.`

- [x] runtime/caml/camlatomic.h:54  https://github.com/ocaml/ocaml/pull/10831#discussion_r775446388
      @xavierleroy `Do we really need to support GCC 4.8? (last released in 2015...)It would be nice to rely on <stdatomic.h> unless absolutely impossible (i.e. unless MSVC).`

- [x] runtime/io.c:201 https://github.com/ocaml/ocaml/pull/10831#discussion_r775583874
      @xavierleroy `I don't understand the logic of this code, and it makes me nervous. Yes, there can be a race between caml_close_channel and caml_ml_out_channels_list. How does this code resolve it?`

- [x] runtime/io.c:502 https://github.com/ocaml/ocaml/pull/10831#discussion_r775584088
      @xavierleroy `Same comment as above. Rather than "let's unlink and ooops let's link again", could we just unlink only when it's safe?`

- [x] runtime/obj.c:188 https://github.com/ocaml/ocaml/pull/10831#discussion_r775588114
      @xavierleroy `I'd rather remove caml_obj_truncate and Obj.truncate entirely, so that we get clean compile-time errors for code that uses it. Note that Obj.truncate has been marked deprecated since 4.09.`

- [ ] runtime/platform.c:244 https://github.com/ocaml/ocaml/pull/10831#discussion_r776438890
       @xavierleroy @gadmm @edwintorok `@gadmm: The original comment has been there unchanged for a while and I propose to remove it. I do not think there is much to gain in trying to fight the overcommitting behaviour on systems that have it enabled. Not failing immediately is overcommitting working as intended (even if it does not produce any interesting difference in this case), and one should instead focus on reliable ways to handle OOM if there is interest in this topic.`

- [ ] runtime/roots.c:34 https://github.com/ocaml/ocaml/pull/10831#discussion_r775599398
      @xavierleroy @kayceesrk `We may revisit this design choice after the merge. The change is fairly easy to implement and benchmark.`

- [x] runtime/callback.c:346 https://github.com/ocaml/ocaml/pull/10831#discussion_r778332227
      @kayceesrk `Not having a lock seems like an omission. We don't have a test for caml_iterate_named_values in the testsuite, which we should.` (#11056)

- [x] runtime/startup_byt.c:381 https://github.com/ocaml/ocaml/pull/10831#discussion_r778346151
      @kayceesrk `Is there a reason why caml_global_data needs to be handled differently in multicore?` (#11051)

- [ ] runtime/obj.ml:32 https://github.com/ocaml/ocaml/pull/10831#discussion_r778348549
       @kayceesrk `Consider for removal.`

- [x] runtime/caml/stack.h:71 https://github.com/ocaml/ocaml/pull/10831#discussion_r778524236 (removed in #11621; arm64 backend re-enabled without it in #10972 and the struct itself which used the macro was removed in #11059)
       @kayceesrk `Unused currently. It was needed earlier for the arm64 backend. May need it again when arm64 is revived.`

- [x] runtime/stdlib.mli https://github.com/ocaml/ocaml/pull/10831#discussion_r778548074
       @kayceesrk `consider renaming EffectsHandlers to Effects`

- [ ] runtime/meta.c:157 https://github.com/ocaml/ocaml/pull/10831#discussion_r778549615
      @kayceesrk `GC can't be triggered in the code; Field no longer includes a read barrier. Make it similar to trunk.`

**Comment by avsm** [comment]
The reason we've pulled out these comments independently of the main issue in #10831 is that we're about to do a force-push to that branch to fix up old committer's names and emails to respect the OCaml mailcap file, and we're not sure if that will result in GitHub losing track of the comments<->hashes as they will have changed.

**Comment by gadmm** [comment]
How soon? I have 30-or-so comment pending I am about to submit, I can send them now or wait and hope it goes well.

**Comment by avsm** [comment]
Waiting is best. In the throes of git gymnastics right now.

**Comment by gadmm** [comment]
Thanks, I did not lose data and could add my review with more outstanding comments.

**Comment by dra27** [comment]
It seems sensible to get towards closing this issue and splitting off things which may want to be addressed in 5.1.

(line numbers given against trunk @ 6a7c70f)

@damiendoligez:
- ~~`runtime/fiber.c` L101, and L168 you have comments to do with possible 32-bit optimisations. Is that worth a separate issue for 5.1?~~ [split off as #11779]

@kayceesrk:
- `asmcomp/cmm_helpers.ml` LL2206-2207 and `runtime/roots.c` L34 (originally - revised in #11189). Although the `FIXME` comments are addressed in #11189, I think the design review (see thread in https://github.com/ocaml/ocaml/pull/10831#discussion_r775599398) is still wanted (and is related to the commenting wanted in `asmcomp/cmm_helpers.ml`). Can this be tracked in a separate issue for 5.1+?
- `runtime/meta.c` L157. `caml_realloc_global` doesn't need the full `CAMLparam` roots infrastructure anymore (this is legacy from the concurrent GC). Track this is in a separate issue for 5.1+?
- `stdlib/obj.ml` LL32-34 proposes removing `Obj.compare_and_swap_field` (which is unused) and `Obj.is_shared` (which is used in the testsuite, but could be declared directly). Track this in a separate issue for 5.1+, given that it's in `Obj`?

@xavierleroy:
- `otherlibs/unix/fork.c` LL40-41. I think `Invalid_argument` is possibly strange here, given that the error is the calling of the function at all, rather than the `()` passed to it (I don't know if we have other instances of this). `Failure` seems possibly more appropriate than `Unix_error` because the issue here is that _runtime_ doesn't support the operation, rather than that there's anything wrong coming from the underlying OS's `fork` implementation?

@xavierleroy / @gadmm:
- `otherlibs/platform.c` L244. I think from reading the comment thread starting at https://github.com/ocaml/ocaml/pull/10831#discussion_r775592329, this possibly boils down to using `MAP_POPULATE` where appropriate. Can this be tracked in a separate issue for 5.1+?

@stedolan:
- ~~`runtime/addrmap.c` L27. Can we add a comment for the source of the hash-function?~~

**Comment by Octachron** [comment]
All remaining items are now covered by separate issues (or PRs) or tracked by individual developers, I am thus closing the meta-issue.
