### ISSUE TITLE
Meta-issue on asynchronous action handling in multicore

### ISSUE THREAD

**Issue by gadmm** [ocaml/ocaml#10915]
### Related issues

- https://github.com/ocaml-multicore/ocaml-multicore/issues/791
- https://github.com/ocaml-multicore/ocaml-multicore/issues/806
- This series of review comments: https://github.com/ocaml/ocaml/pull/10831#pullrequestreview-847201882

### Action points

First in any order:
- [x] Review the diff of `finaliser.c` between multicore and old trunk to make sure nothing is missing; reimplement `caml_final_do_calls_exn`.
- [x] Separate signalling from payload for inter-domain interrupts. Record the request for an interrupt separately from young_limit to distinguish the various asynchronous actions to perform when an allocation fails.
- [x] Discuss atomicity of young_limit (https://github.com/ocaml/ocaml/pull/10831#discussion_r780720290).

Then (in order):
- [x] `caml_alloc_small_dispatch` is a common entry point to the GC (restore its subtle logic)
- [x] Reimplement `caml_do_pending_actions_exn`/`caml_process_pending_actions_exn`
- [x] Minimise the diff with old trunk (check that nothing misses; preserve relevant bits of memprof implementation to avoid to forget things later on); make sure that there is no unjustified change to `caml/signals.h` and `caml/alloc.h`.

I think those are a pre-requisite for 5.0 (public API in actual use and the documented way to poll in long-running C functions). If not possible, at the very least, `caml_process_pending_actions_exn` should be reintroduced with a partial implementation.

### Checklist for expected behaviours

The following are needed for 5.0:

- [x] `caml_check_urgent_gc` runs pending GC actions including inter-domain interrupts; no asynchronous callbacks. Idem when handling an inter-domain interrupt.
- [x] A function `update_young_limits` is used to locally set young_limit to the right value according to various pending action flags (signals, finalisers, inter-domain interrupts...), to make sure young_limit is always set to the right value.
- [x] `caml_process_pending_actions_exn` does not raise directly into OCaml.
- [x] `caml_do_pending_actions_exn` informs of possible future actions if interrupted by an exception.
- [x] finalisers do not run immediately when allocating from C; restore the guarantee at the top of `caml/alloc.h`.
- [x] Reintroduce `caml_something_to_do` and its logic?
- [x] Events are properly stopped in case of an asynchronous exception inside `runtime/gc_ctrl.c`.
- [x] `caml_leave_blocking_section` checks for signals like it used to.
- [ ] `Gc.alarms` work as intended.

The following are not strictly needed for 5.0 (but most are likely fixed along with the rest).

- [x] OCaml signal handlers are guaranteed to be run as soon as possible.
- [x] No need for `caml_handle_gc_interrupts_no_async`.
- [x] `caml_process_pending_actions*` is the single entry point to run all pending actions (no separate `caml_process_pending_signals*`).
- [x] When recording a backtrace, no need to assume that finalisers could run.
- [x] The VM polls by comparing young_limit to young_ptr; investigate https://github.com/ocaml/ocaml/pull/10880#issuecomment-1012005841.

(cc @sadiqj, @jhjourdan)

**Comment by gadmm** [comment]
We discussed the issue yesterday with @sadiqj. The GC design has changed in multicore and the goal was to come up with a plan to fit the old control over asynchronous exception/callbacks with the new GC design.

We both would like that it is seen as preliminary work to restore StatMemprof so that it gets appropriate attention.

The previous code essentially made a clear separation between two kinds of tasks:
- What cannot be delayed (e.g. needed to complete an allocation) but may never raise.
- What may raise, but can be delayed.

The new GC on the other hand has a subtle logic between the marking of ephemerons, finalisers, and finishing a major cycle, described in the “Retrofitting” paper and checked with a model checker. We want to make sure not to touch this part and we needed to make sure that it was possible to decouple the running of finalisers from the rest of the GC.

After looking at the code we think that the new GC can easily implement the separation in one form or another, so we do not expect major technical hurdles. In particular it should be the case that a stop-the-world section can always synchronise on any polling location, even those not ready to receive exceptions, because no asynchronous callback is required to run during STW (currently, finalisers are run at the end of minor GC, right after STW).

However in terms of timeline it may or may not be completely ready for 5.0. (So the very first step is probably to restore the previous public APIs and document what does not yet work as intended.)

During the discussion it appeared that Gc.alarms have probably not yet been tested in multicore.

**Comment by gasche** [comment]
As far I know, the topic remains important and the work is not finished, so I am reopening. In particular the following PRs are in the air and could make progress if people were able and willing to review them:

- the work on "quality treatment of asynchronous actions", https://github.com/ocaml/ocaml/pull/11057, which is itself a sort of meta-PR whose latest increment PR is https://github.com/ocaml/ocaml/pull/11307
- the work on masking asynchronous actions: https://github.com/ocaml/ocaml/pull/8961 (this PR needs a rebase on top of the Multicore runtime, which is probably a fair amount of work; before asking @gadmm to rebase we should see if we have volunteers to review it)

**Comment by gadmm** [comment]
The last PR has been merged (#11307), so we can close this issue as resolved.

Regarding Gc alarms (a callback called at the end of each major GC cycle), it looks like the difference in which finalisers are implemented changes how often the callback is called. In OCaml 5, they are called less than 1 every two major cycles. However, they were not systematically called already in OCaml 4 (they would fail to trigger something like 1 out of 5 times). Given the use of GC alarms in the wild (e.g. memory limits), we can therefore expect that they will behave functionally the same. The current documentation is a bit misleading though as it incorrectly claims that Gc alarms are called at the end of every cycle.
