### ISSUE TITLE
GitHub Actions / ocamltest / testsuite / OCaml 5

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml#10980]
The GitHub Actions received a very welcome overhaul from @Engil as part of the multicore effort. There are a few things which can still be worked on (and a couple of checks which might need restoring).

This issue is a tracking issue for various things @Engil and I just discussed. Also, of course, cc'ing @shindere for comments!

- [x] The `linux-debug` job should be able to use the cached compiler and be moved to the testsuite matrix? It's not on the slow path, but saves carbon and frees up runners more quickly.
- [x] Factor out the lists of individual directories to an environment variable at the top of the workflow just for consistency (and to allow ones to be added easily). These are for tests the the `-O0` and the small stack tests where several sets of test directory names are hard-coded at the moment.
- [x] Commenting in `build.yml` as to why workflows are tested (e.g. the `-O0` has been a good bug-smoker in the past, apparently)
- [ ] Possible improvements on use of `actions/upload-artifact`:
  - [ ] Excluding the `.git` directory (although it is a shallow clone, so it won't be too large)
  - [ ] Excluding .cmt and .cmti and possibly .o files
  - [x] Using zstd which _might_ be faster to compress
- [x] Consistently use `SHOW_TIMINGS=1` so that all the summaries get "Tests taking longer than 10s"
- [x] We should be using `make parallel` for the testsuite (partial work in #10760 - this is likely to be a huge win for overall workflow time for macOS)
  + [ ] Extend `ocamltest` to have tests marked as "not-to-be-run-in-parallel"
  + [ ] Using this new attribute and ocamltest's test-searching functions to allow `make -C testsuite parallel` to run the tests marked "not-to-be-run-in-parallel" serially and then _the rest_ of the testsuite in parallel
  + [ ] Use this in CI (i.e. #10760)
- [ ] Add a command-line flag for testing bytecode-only or nativecode-only (missing since ocamltest was adopted).
- [x] The `other-checks` runner stage needs to be restored! In particular, we're not doing the check-all-arches tests
- [x] Fault in `summarize.awk` noted in #10953
- [ ] #1024 - being able to test installations (as an alternative to the build tree). This isn't critical, but there are now several advantages:
  + flambda 2.0 testing could do with this (at present, it has to take an installed tree and copy it back to a source tree to run the testsuite)
  + Our CI can then have an easy and more efficient upload-artifact of just the installation directory and ocamltest itself
  + It opens the possibility of being able to bisect very easily with _newer_ tests

**Comment by xavierleroy** [comment]
> Extend ocamltest to have tests marked as "not-to-be-run-in-parallel"

I've been using "make parallel" for trunk testing without realizing that some tests should not be run in parallel.  Why is that so?

**Comment by dra27** [comment]
> > Extend ocamltest to have tests marked as "not-to-be-run-in-parallel"
> 
> I've been using "make parallel" for trunk testing without realizing that some tests should not be run in parallel. Why is that so?

I have been too (routinely - I never run `make all` these days!). For developer systems (probably with high, or at least >2, core counts) it's fine. The idea with that proposal is to mark the tests which _intentionally_ spin up multiple domains and where running them in parallel will over-commit the CI worker.

**Comment by shindere** [comment]
> This issue is a tracking issue for various things @Engil and I just
> discussed. Also, of course, cc'ing @shindere for comments!

Thanks!

> - [ ] The `linux-debug` job should be able to use the cached compiler
> and be moved to the testsuite matrix? It's not on the slow path, but
> saves carbon and frees up runners more quickly.

What do you mean by cached compiler? And by testsuite matrix?

> - [ ] Factor out the lists of individual directories to an environment
> variable at the top of the workflow just for consistency (and to
> allow ones to be added easily). These are for tests the the `-O0`
> and the small stack tests where several sets of test directory names
> are hard-coded at the moment.

Could you explain a bit more here, too?

> - [ ] Possible improvements on use of `actions/upload-artifact`:
>   - Excluding the `.git` directory (although it is a shallow clone, so it won't be too large)
>   - Excluding .cmt and .cmti and possibly .o files
>   - Using zstd which _might_ be faster to compress

zstd?

> - [ ] Consistently use `SHOW_TIMINGS=1` so that all the summaries get "Tests taking longer than 10s"
> - [ ] We should be using `make parallel` for the testsuite (partial work in #10760 - this is likely to be a huge win for overall workflow time for macOS)
>   + [ ] Extend `ocamltest` to have tests marked as "not-to-be-run-in-parallel"

Shall we introduce an ocamltest variable for that?

For instance, it could be called `can_be_run_in_parallel` and would be
set to true by default and those test which cannot be run in parallel
would set it to false. That would be easy to add to ocamltest because it
woulnd't require any change to the DSL and then external tools could
grep the test files for that assignment.


>   + [ ] Using this new attribute and ocamltest's test-searching functions to allow `make -C testsuite parallel` to run the tests marked "not-to-be-run-in-parallel" serially and then _the rest_ of the testsuite in parallel

I thought about putting the tests that can not be run in parallel in a
specific directory to make this simpler but I assume it won't be
satisfactory to decide where the test should reside in the testsuite
just because of whether it can be runin parallel with other tests or
not.

> - [ ] Add a command-line flag for testing bytecode-only or
> nativecode-only (missing since ocamltest was adopted).

Do you mean to make this independent of which compiler has been
compiled? I mean, you would like to be able to run only bytecode tests
even if both compilers have been compiled, and the same for running only
native-code tests?

One possibility would be to introduce tags for tests andthen you could
pass those tags to ocamltest to define which tests should be run. The
point is, if a tag is attached to each test, it requires a bit of
thinking to determine how this mixes with test trees and perhaps
testsequence. In principle I imagine a test-tree would contain only
tests with the smae tag, but I am not sure. Perhaps one could run the
tests iin a tree until a node is reached whose tags do not match the
expected ones and not go deeper. Same for test sequences: run the tests
in a sequenceuntil a test is met whose tags do not mattch the requested
ones and stop there. I don't know whether we would need such a feature
one day but just trying to think out loud about how it could be
implemented in a principled way.

> - [ ] #1024 - being able to test installations (as an alternative to the build tree). This isn't critical, but there are now several advantages:
>   + flambda 2.0 testing could do with this (at present, it has to take an installed tree and copy it back to a source tree to run the testsuite)
>   + Our CI can then have an easy and more efficient upload-artifact of just the installation directory and ocamltest itself
>   + It opens the possibility of being able to bisect very easily with _newer_ tests

I very much like this one.

My understanding is that the main problem is that the paths of tools and
libraries in the source tree are not in any way related to what they
will be in the installed tree.

I can imagine two solutions to this problem.

 1. Introduce two modes to ocamltest, one to test from source tree and one to test from install tree.
 2. Try to dissociate source tree and build tree so that the build tree can be made similar to the install tree.

Solution #1 would not be too difficult to implement, I think. Solution
#2 is of course more work but I was kind of hoping that it would come as
a nice side-effect of the work aiming at being able to build the
compiler out-of-source tree. Yet another benefit of this feature.

Thoughts welcome on all these!

**Comment by abbysmal** [comment]
Hello!

Thank you for your answer!

> What do you mean by cached compiler? And by testsuite matrix?

Multicore OCaml introduce the use of Github's build artifacts as a way to cache a build of the compiler for subsequent testsuite runs.
We extended our testsuite runs on Github by adding different parameters (the testsuite matrix that you just mentioned.)
The current setup basically works as such:
- A build action will the compiler tree, with no added parameters to `configure`
- This tree will be compressed and uploaded as a build artifact to Github. (and will expire after 24 hours).
- A few jobs are then started, that will first download this compiled tree:
  - One job will run the full testsuite, with no extra OCAMLRUNPARAMs.
  - Then there will be more jobs, running the testsuite (or specific parts of the testsuite) with various constraints: low minor heap, locking execution of parallel tests to one core only, and full debug run of the testsuite.
  
To note, there are extra runs that cannot reuse said build artifacts, because they rely on specific builds of the compiler using specific configure options. These are done in separate dry runs. (because they need to build the compiler with specific settings anyway.).
And of course the MacOS job is separate because the artifacts are from a Linux job and the MacOS testsuite run is just a simple one.

> zstd?

We were pondering upon using a different tool to compress/decompress the aforementioned compiler build artifact. (currently LZMA2).
Zstandard is a pretty good candidate (and is available on Github CI machines).
See: http://facebook.github.io/zstd/

I actually pushed a branch doing just that, with pretty decent results, shaving a minute and a half: https://github.com/ocaml/ocaml/pull/10991

>> - [ ] Consistently use `SHOW_TIMINGS=1` so that all the summaries get "Tests taking longer than 10s" - [ ] We should be using `make parallel` for the testsuite (partial work in #10760 - this is likely to be a huge win for overall workflow time for macOS) + [ ] Extend `ocamltest` to have tests marked as "not-to-be-run-in-parallel"

> Shall we introduce an ocamltest variable for that? For instance, it could be called `can_be_run_in_parallel` and would be set to true by default and those test which cannot be run in parallel would set it to false. That would be easy to add to ocamltest because it woulnd't require any change to the DSL and then external tools could grep the test files for that assignment.

I think this works fine indeed!

> Do you mean to make this independent of which compiler has been compiled? I mean, you would like to be able to run only bytecode tests even if both compilers have been compiled, and the same for running only native-code tests? One possibility would be to introduce tags for tests andthen you could pass those tags to ocamltest to define which tests should be run. The point is, if a tag is attached to each test, it requires a bit of thinking to determine how this mixes with test trees and perhaps testsequence. In principle I imagine a test-tree would contain only tests with the smae tag, but I am not sure. Perhaps one could run the tests iin a tree until a node is reached whose tags do not match the expected ones and not go deeper. Same for test sequences: run the tests in a sequenceuntil a test is met whose tags do not mattch the requested ones and stop there. I don't know whether we would need such a feature one day but just trying to think out loud about how it could be implemented in a principled way.

Right, what would be nice would be to pick whether we want to run native or bytecode no matter the state of the compiled tree.
I was initially thinking of a far less principled approach but reading your answer makes me realize this idea would have never worked in any way whatsoever. :-)
I will ponder upon your response and will come back after thinking about it.

**Comment by shindere** [comment]
Regarding the `not-to-be-run-in-parallel` suggestion:

It seems to me that, with this wording, what would be described would be
an attempt to give a hint on how to run the test (in parallel or not).

But that, after all, may depend on the environment and is not an intrinsic
property of the test itself.

Rather than that, how about introducing " `cores` ocamltest variable?
Its default value would be 1 but the tests which require more than
one core could override it and give a more precise indication on how
many cores they require.

In addition, ocamltest could have a `-max-cores` option and it would
skip those tests which require more cores than it has been given.

That way the CI infrastructure could specify how many cores are
available, for each slave.

Would that seem reasonable?

**Comment by abbysmal** [comment]
> Rather than that, how about introducing " `cores` ocamltest variable? Its default value would be 1 but the tests which require more than one core could override it and give a more precise indication on how many cores they require.
> 
> In addition, ocamltest could have a `-max-cores` option and it would skip those tests which require more cores than it has been given.

I think this is quite interesting and partly address one overarching concern I have about the parallel segment of the Multicore testsuite:
As it stands right now, test spawning multiple domains do so in an arbitrary fashion with a number of domains they pick in the test code itself, meaning it is hard to know their requirements, and hard to adjust them.
I like you suggestion as it fixes this specific issue (we will now know the requirements and can decide how to run them), and streamlines the level of parallelism of such tests.

**Comment by xavierleroy** [comment]
> As it stands right now, test spawning multiple domains do so in an arbitrary fashion with a number of domains they pick in the test code itself

This is not quite right.  I introduced the `OCAML_TEST_SIZE` environment variable to give tests a hint of how many cores they can expect: https://github.com/ocaml/ocaml/blob/trunk/testsuite/HACKING.adoc#creating-a-new-test .  It's effective to avoid parallel tests that time out because they spawn too many domains for a 2-core VM.

Nonetheless, it might be useful to have ways to run the parallel tests sequentially, even if we do `make parallel` at the top of the test suite, so that each parallel test has all the cores to itself.  But maybe it's not a problem to have a parallel test running in parallel with a sequential test, after all...  So let's not over-engineer a solution to a possibly nonexistent problem.

**Comment by abbysmal** [comment]
> This is not quite right. I introduced the `OCAML_TEST_SIZE` environment variable to give tests a hint of how many cores they can expect: https://github.com/ocaml/ocaml/blob/trunk/testsuite/HACKING.adoc#creating-a-new-test . It's effective to avoid parallel tests that time out because they spawn too many domains for a 2-core VM.

Indeed, I missed this, thank you for pointing it out.
 
> Nonetheless, it might be useful to have ways to run the parallel tests sequentially, even if we do `make parallel` at the top of the test suite, so that each parallel test has all the cores to itself. But maybe it's not a problem to have a parallel test running in parallel with a sequential test, after all... So let's not over-engineer a solution to a possibly nonexistent problem.

I wonder if the question of running sequentially a parallel test could not be solved through `taskset`. (pinning runs to one core only.)
This is a testsuite run scenario we used to have on Multicore (and is useful on parallel testcases for getting out some odd synchronizations scenarios.)
Maybe this could be a generalized approach to constraining the number of core to be used by parallel testcases as well.

About the initial post:
I have a PR coming in the next few days involving a refactor of the Github Actions code, streamlining a few testsuite scenarios, and possibly improving on the running times.
I am very much not happy with the current state of the code (which I mostly attribute to myself with the few Multicore additions I made over the last year.), and a spring cleanup is in order.

**Comment by shindere** [comment]
Thanks for the explanations, which I am not going to quote.

I will just quote one bit of your comment:

> > Shall we introduce an ocamltest variable for that? For instance, it could be called `can_be_run_in_parallel` and would be set to true by default and those test which cannot be run in parallel would set it to false. That would be easy to add to ocamltest because it woulnd't require any change to the DSL and then external tools could grep the test files for that assignment.
>
> I think this works fine indeed!

That's I think superseeded by the idea I gave about a `cores` variable.

> > Do you mean to make this independent of which compiler has been compiled? I mean, you would like to be able to run only bytecode tests even if both compilers have been compiled, and the same for running only native-code tests? One possibility would be to introduce tags for tests andthen you could pass those tags to ocamltest to define which tests should be run. The point is, if a tag is attached to each test, it requires a bit of thinking to determine how this mixes with test trees and perhaps testsequence. In principle I imagine a test-tree would contain only tests with the smae tag, but I am not sure. Perhaps one could run the tests iin a tree until a node is reached whose tags do not match the expected ones and not go deeper. Same for test sequences: run the tests in a sequenceuntil a test is met whose tags do not mattch the requested ones and stop there. I don't know whether we would need such a feature one day but just trying to think out loud about how it could be implemented in a principled way.
>
> Right, what would be nice would be to pick whether we want to run
> native or bytecode no matter the state of the compiled tree.

The two things can not be completely decoupled. You can't run native
tests if the native compiler has not been compiled, forinstance. But I
guess you meant coupled in a less tight way than now.

> I was initially thinking of a far less principled approach but reading your answer makes me realize this idea would have never worked in any way whatsoever. :-)
> I will ponder upon your response and will come back after thinking
> about it.

So suming up the recent exchanges, it feels like we would need to
perform two kinds of checks to decide whether a test should be run or
not: a tag-based check and a ressource-based check. Only the tests that
satisfy htese two prerequisites would be run.

**Comment by xavierleroy** [comment]
Could we get an update on the 13 (!) tasks proposed in this issue?  At any rate, none of them should block 5.0, so I'm taking the 5.0 milestone off.

**Comment by xavierleroy** [comment]
Actually, let me add a 14th task: add a Github action that tests on ARM 32 bits.  Not x86 32 bits, that's too easy because the processor provides 64-bit atomic operations.  ARM 32 bits has been broken repeatedly by recent pull requests, so if we're serious about supporting 32-bit platforms, more CI is needed.

**Comment by abbysmal** [comment]
I updated the list following the merge of #11183.
@xavierleroy I do have an ARM 32 bits runner PoC on the grill, I need to make a few adjustments and it will be ready.
