### ISSUE TITLE
Meta-issue on the semantics of the Bytes/String divide (representation, onwership-safe functions, optimizers and all that)

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml#9451]
Over in #9448 a discussion erupted about what is the "truth" on the semantics of the `Bytes.unsafe_{to,of}_string` functions. Are they lying about the (im)mutability of their argument or result, can an optimizer assume that they don't exist? Do we specificy that these two types have the same representation, or do we only not-not-specify it, that is, consider that anything that either enforces or requires it is incorrect?

I am creating this meta-issue to track this discussion.

**Comment by dra27** [comment]
Actually, the discussion erupted on #9448!

**Comment by lthls** [comment]
From a middle-end developer's point of view: the solution we have now treats constant strings as shareable but all strings are considered mutable. This disables some optimisations, so at some point in the future we'd like to handle strings as immutable.

The two unsafe functions are problematic because, just like `Obj.magic`, they would be unsound in this context.
The `unsafe_to_string` one could be replaced by a special kind of identity that tells the compiler "I'm not going to change it anymore, assume it's immutable now". This can be handled fairly well by the compiler, and we could have flags to switch between blindingly accepting the statement, make a copy, or try to prove nobody can change the contents.
The `unsafe_of_string` one should disappear, or explicitly copy. There shouldn't be anything that you can do with a `bytes` that you cannot do on a `string`, except things that mutate the contents, and mutating something you've declared as immutable is very problematic. I'm aware that it is used a number of times in `String`, but I think that this should be fixed by writing the corresponding functions to take a `string` argument and return a `bytes` result, and then both `Bytes` and `String` could make use of them using only `unsafe_to_string`.

As a first step, I would welcome moving `unsafe_of_string` to `Obj` to send a message to developers that using it will likely break things in the future.

**Comment by nojb** [comment]
> As a first step, I would welcome moving `unsafe_of_string` to `Obj` to send a message to developers that using it will likely break things in the future.

Instead of moving the function, which will necessitate a long discussion, we could use the existing "alert" infrastructure:

```
val unsafe_of_string: string -> bytes
[@@alert unsafe "this will likely break things in the future!"]
```

to emit an alert at every use of the function.

**Comment by lthls** [comment]
Yes, good point. Although I think we could also put the definition in `Obj` early, to put an emphasis on the fact that it's now considered as dangerous as the rest of `Obj`, and allow for a sufficiently long period where both functions are available when we want to remove it from `Bytes` in the distant future.

**Comment by yallop** [comment]
I don't see any need to remove or rename the `unsafe_*_string` functions for the moment, or even to warn about them.

If it becomes necessary to introduce copying in the future because the representation changes, or because the optimizer becomes more aggressive then they can be deprecated in favour of the safe versions.  But even though the pragmatics will change the semantics can stay the same, so there's no need to ever actually remove them.

**Comment by gasche** [comment]
Personally my view is that, currently, very few choices have been made/specified. This is what I understand of the current state:

- We should not assume that strings and bytes have the same representation (I think that code that does this is incorrect), but that does not preclude having the `unsafe_{to,of}_string` primitives in the library (they could do a shallow copy of some sort that is more efficient than the safe versions).

- Shared-ownership strings are immutable, but it is currently unspecified whether unique-ownership strings are mutable or immutable. The OCaml compiler does not have a way to statically enforce this ownership discipline, but we can still describe it when we try to specify this corner of the language or reason on compiler optimizations.

- `unsafe_of_string` is fine as long as the resulting `bytes` is never mutated. This design introduces the notion of "immutable bytes" in the mental model, which are those that come from strings. (Again, the language does not statically enforce this, but we can still reason about it.)

If we decide that even uniquely-owned strings are immutable then `unsafe_to_string` corresponds indeed to the "immutable from now on" primitive that @lthls mentioned. (If we decide that they are mutable, then that different model, more liberal model allows to mutate the result `unsafe_of_string (unsafe_to_string bytes)`.)

Regarding compiler optimizations, I see three possible approaches:

1. Given that *some* strings may be mutable, assume that all strings may be mutable. This is a pretty safe choice and I think it should be the reasonable first approach unless there are clear, demonstrated benefits to doing anything more complex. @lthls, is there any concrete evidence that treating all strings as immutable will bring us performance gains?

2. Let the optimizer rely on ownership and mutability facts that it is able to prove from the current code. Unfortunately this is pretty limited; it is possible to prove that a value is uniquely owned, but I don't see how to prove that a value has shared ownership -- so that is not very different from (1) from an optimization point of view.

3. We could decide that the optimizer is allowed to assume that the ownership discipline is respected; that there are no obligation to preserve the mutable updates to strings and bytes objects for ill-owned programs (but only this; in particular they must remain well-typed so this preserves other safety properties of the language).

The following changes to the model have been mentioned to restrict and simplify it:
- Enforcing that all values of type string are immutable; this is very reasonable.
- Disallowing `unsafe_of_string`, even for read-only usage of string; this is possible but needs further discussion.

This would probably result in the best design in term of compromises between static safety and performance (we have a simple enough model, that lets us keep the efficient pattern of initializing strings as bytes), it agrees with @lthls' view, but still I don't think this restricted model was ever clearly specified, decided and accepted.

**Comment by yallop** [comment]
> Personally my view is that, currently, very few choices have been made/specified. This is what I understand of the current state:
> [...]
> Shared-ownership strings are immutable, but it is currently unspecified whether unique-ownership strings are mutable or immutable. 

It's clearly specified that strings are immutable.  (See the [`String` module documentation](https://github.com/ocaml/ocaml/blob/67ada54ce36e9d52cf8332285d2b6e2118ebf998/stdlib/string.mli#L18), the [manual](https://github.com/ocaml/ocaml/blob/67ada54ce36e9d52cf8332285d2b6e2118ebf998/manual/manual/tutorials/coreexamples.etex#L53-L66), the [changelog](https://github.com/ocaml/ocaml/blob/67ada54ce36e9d52cf8332285d2b6e2118ebf998/Changes#L3401-L3402), the [compiler help text](https://github.com/ocaml/ocaml/blob/67ada54ce36e9d52cf8332285d2b6e2118ebf998/driver/main_args.ml#L492-L493), etc.)

If there's anything in the `Bytes` documentation that conflicts with the fact that strings are immutable then we should update it.

**Comment by gadmm** [comment]
Thanks for writing that @gasche, this is almost what I wanted to say, so I'll be brief. (You meant "Disallowing `unsafe_of_string`, right?)

@yallop does not believe that aliasing unsafe functions for their safe counterparts breaks programs, but I think it does break the performance guarantee that has been given to users (or they could ask: why were they introduced in the first place?). If so, introducing silent bugs is worse than giving them a warning. I mainly wanted to emphasize as I did in the other thread that before considering breaking this guarantee, one should investigate clever ways of changing the representation of string while keeping the guarantee when it matters (and even others cases like flattening a non-atomic rope could be reasoned as simply moving the cost around).

Also, I believe it would be fine to assume that all strings are immutable and that there is no need of a notion of “uniquely-owned” string, a notion of “immutable from now on”, or to further discourage `unsafe_of_string` (the documentation is already clear about the limitations). Let us review the official cases:

- [x] Publish a string after creating it as byte, as mentioned.
- [x] Lend a bytes as string to a function that does not leak the string. I do not see how optimisations based on immutability can create new aliases of the string that will leak (do you have something in mind here?). So the bytes can safely be mutated after the function returns. (There is a catch here.)
- [x] Pass a string to a function that expects a byte but does not mutate it. (I do not like the notion of “immutable bytes”, because it is a property of the function, not of the value.) From an optimisation perspective, it is always correct to assume that something immutable is mutable, because it means that fewer optimisations are applied.

I mentioned a catch. The notion of "leaking" for a string changes depending on the representation. I bet it is easy to find functions in the wild that do not leak (e.g. concatenation), but that start leaking their argument if strings were implemented as ropes. But I see this as a problem about changing representation, not about assuming immutability as the problem is already there without it.

I write this without any survey of opam packages, only based on the specification. Any proposed change should be evaluated against a good sample of code in the wild. One should expect surprises, maybe even legitimate ones. And let us keep in mind that there is a good reason that the topic of expressiveness vs. aliasing vs. mutability is difficult, and so maybe some of the code in the wild is wild for a good reason.

**Comment by yallop** [comment]
@gadmm: I agree with almost everything you've written (especially the idea of removing the notion of "“uniquely-owned” string"), so let me just clarify one point:
>@yallop does not believe that aliasing unsafe functions for their safe counterparts breaks programs, but I think it does break the performance guarantee that has been given to users (or they could ask: why were they introduced in the first place?). If so, introducing silent bugs is worse than giving them a warning. 

Yes: if we were to switch to a copying implementation of the `unsafe_*_string` functions then we should simultaneously introduce a warning for the reason you mention.  While the behaviour wouldn't be semantically incorrect, it would be sufficiently surprising to justify alerting the user.

**Comment by gadmm** [comment]
@yallop 
> If there's anything in the `Bytes` documentation that conflicts with the fact that strings are immutable then we should update it.

Only the following does not make much sense to me:
> Assuming unique ownership of strings that are not string literals, but are (partly) built from string literals, is also incorrect. For example, mutating [unsafe_of_string ("foo" ^ s)] could mutate the shared string ["foo"] -- assuming a rope-like representation of strings.

`unsafe_of_string` should not be used to "assume unique ownership", because all strings should be assumed possibly-aliased (but it does not clearly say that assuming unique ownership is ever possible). Moreover, in a hypothetical extension of string as ropes, there must be some flattening happening during unsafe_of_string when necessary, so the hypothetical is bogus.

Also the following:
>    In practice, unique ownership of string values is extremely
    difficult to reason about correctly. You should always assume
    strings are shared, never uniquely owned.

Again, it does not say that unique ownership of string values is ever possible to reason about.

If find that the documentation says that a string should only ever be passed to functions that do not mutate their bytes argument, but in a very roundabout way.

**Comment by gadmm** [comment]
@yallop It is true that I changed my view in the course of the conversation. From the moment all literals are assumed shared, and all result of functions must be assumed shared, there was just no meaningful way of manipulating uniquely-owned strings.

**Comment by lthls** [comment]
For performance gains, on paper this should allow us to reuse previous accesses to the same element, although this is rather uncommon, and consider string reads as pure, allowing us to move them around freely, but again I don't think we will gain much from it in practice. We may at some point start to record the purity of functions, in which case it could make bigger gains as it could turn a non-pure function into a pure one, but this is just speculation.
If we start using read-only data sections for immutable constants, it may make a small change to allow strings there too.

If someone wants to see what would change, I could work on a PR to remove all uses of `unsafe_of_string` in the stdlib (the only change in the API would be some new exported functions in `Bytes` for use in `String`, or a new internal module that `Bytes` and `String` would depend on).

**Comment by yallop** [comment]
@lthls: indeed, it would be interesting to know whether there are optimization opportunities arising from string immutability.  I expect that you're right, and there's not a great deal to be gained, but perhaps some catenations of literals that show up after inlining could be performed statically.

While we're discussing plans, I should say that I'm planning to investigate alternative representations of strings with an intern over the summer.  I'm particularly interested in representations that interact nicely with the garbage collector, such as ropes that are flattened during promotion/compaction (in a similar way to the elimination of forward pointers in forced lazy values).

**Comment by gasche** [comment]
On `unsafe_of_string`. I agree that it is sensible to consider all strings immutable. Then `unsafe_of_string` is only ever correct if the resulting `bytes` is not mutated. This use-case was important during the transition period (and please keep in mind that a lot of code is exactly the result of the transition period).

One way to think of it is that `Bytes.t` are defined as a "ghost variant": either a mutable byte sequence or an immutable byte sequence. Writes on immutable sequences are an unsafe programming error; they can crash the program, but they must not break type-safety.

Note: but yes, if we deprecate `unsafe_of_string` we can simplify this model for Bytes and only ever have mutable bytes, and get rid of the "mildly-undefined-behavior" part that unpleasantly reminds us of C semantics. The thing is that deprecating `unsafe_of_string` may some amount of work in practice, and have other externalities (code duplication, etc., as we discussed in the original PR).

On `unsafe_to_string`: even if we move to a different representation of strings, in many cases it is important for performance reasons to allow to an embedding a byte sequence in this representation without doing a copy. This is part of the programming model so (as @gadmm) I think it is part of an ideal specification of the language.

If other operators (like concatenations) are changed to share/leak their input instead of copying it, then we can:
- Share/leak the byte sequence: programs that respect the ownership discipline will behave correctly, others remain type-safe.
- Do a copy at this point (presuming the embedding retains the uniquely-owned information), exactly like in usual copy-on-write schemes (except here it is more copy-on-leak). Being able to delay copies in this way can already be a win for performance.

**Comment by yallop** [comment]
> in many cases it is important for performance reasons

It'd be useful to have some concrete examples of the important cases.  It'll be much easier to judge possible solutions once there's agreement on what the problems are.

**Comment by gasche** [comment]
One typical example would the implementation of `really_input_string : in_channel -> length:int -> string`. Your low-level input functions mutates byte sequences, so you need to allocate a bytes of the output length to call them, and then you don't want to also allocate a string (I would guess that in many cases the allocation is more annoying than the copy itself). If you are reading from an input device that sends a lot of IO (say gigabits per second), you are allocating just as much, and you don't want to allocate twice as much.

Then it may even be possible to use a fixed-size bytes buffer to read the data, and convert that into a string to pass it to your inner processing step, *if* you know that this processing step does not leak/share the string (it returns ownership on termination). This design requires making more assumptions on your code, but then you can read data fast with no allocation anymore -- no more than what your IO system is already doing.

**Comment by hhugo** [comment]
> The zero-cost convertibility between bytes and string is part of the design and documentation of the Bytes and String modules, and the documentation indicates several safe ways users can leverage this convertibility (for instance to create a string using mutations before publishing it as an immutable value). To me it seems wrong to treat it only as an implementation detail. If js_of_ocaml gave up the zero cost, then I think users would be correct if they complained that js_of_ocaml introduces buggy behaviour in correct OCaml programs (depending on what promises are made to users).

@gadmm If you put apart additional allocations (which are not observable in JavaScript), I fail to see any other buggy behaviors that this could introduce.

**To give some context about jsoo:**
Js_of_ocaml already allow different representation for string vs bytes at the tip of the repo, under a flag.
In js_of_ocaml, bytes are implemented with a polymorph javascript object containing a mutable field that is either a js-string (truly immutable & behaving as if hashcons-ed) or an array of char/integer. The shape differs depending on the usage.

When enabling the different representation between string and bytes in js_of_ocaml, strings are represented as immutable JavaScript strings (instead of bytes with the representation described above).
- converting from bytes to string may or may not be zero-cost
- converting from string to bytes will just allocate the object wrapper around the string

**Comment by gadmm** [comment]
@hhugo Yes, I agree that it should only be a performance distinction—a visible bug when enabling js strings would be a bug in the original OCaml program. And given your explanations, it does seem that some cost has to be paid at some point. I do not see anything better than letting users chose their model as you already do. Maybe the current clarification will help js_of_ocaml users better evaluate the tradeoff.

**Comment by hhugo** [comment]
> If someone wants to see what would change, I could work on a PR to remove all uses of `unsafe_of_string` in the stdlib (the only change in the API would be some new exported functions in `Bytes` for use in `String`, or a new internal module that `Bytes` and `String` would depend on).

I removed usage of `unsafe_of_string` from the `String` and `Bytes` modules, see https://github.com/ocaml/ocaml/pull/9789
The current approach rely on code duplication.
